"""Read and write the ngscope TOML config.

Writing is hand-rolled rather than pulling in tomli-w: the schema is flat (scalars, one
array of tables, one sub-table) so the emitter is a dozen lines, and the GUI stays a
single-dependency install.

Reading uses stdlib tomllib, and goes through the same schema, so a file hand-edited
outside the GUI round-trips as far as the schema covers it.
"""

import tomllib
from datetime import datetime
from pathlib import Path

from . import earfcn, schema


# --------------------------------------------------------------------------- emitting


def _scalar(value, type_):
    if type_ == "bool":
        return "true" if value else "false"
    if type_ in ("int", "int64", "mode"):
        return str(int(value))
    # str / path
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _emit_fields(lines, fields, values, replaying=True):
    for field in fields:
        key = field["key"]
        value = values.get(key, field["default"])
        # replay_fname is a borrowed const char* defaulting to NULL on the C side; an
        # empty string is not the same thing, so omit the key entirely when unset.
        if field["type"] == "path" and not value:
            continue
        # A replay-only setting is emitted at its schema default when nothing is replaying.
        # The user's replay-time choice stays in GUI state, but it must not reach a live
        # config: ngscope refuses mark_security_phase outside mode 2, so a value left over
        # from an earlier replay session would abort the run over a setting the form does
        # not even show in that mode.
        if field.get("replay_only") and not replaying:
            value = field["default"]
        # mode_locked is per cell, so it is applied against this table's own mode value.
        locked = field.get("mode_locked")
        if locked and values.get("mode") in locked:
            value = locked[values["mode"]]
        lines.append(f"{key} = {_scalar(value, field['type'])}")


def dumps(model):
    """Render the config model as ngscope-flavoured TOML."""
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "# Generated by ngscope-gui on " + stamp + ".",
        "# Regenerated on every launch -- edit the settings in the GUI, not this file.",
        "",
    ]

    replaying = any(c.get("mode") == schema.MODE_REPLAY for c in model.get("cells", []))
    _emit_fields(lines, schema.TOP_LEVEL, model.get("top", {}), replaying)

    # nof_rf_dev is intentionally not emitted: the TOML backend derives it from the
    # number of [[rf_config]] tables (load_config_toml.c:174-183).
    for cell in model.get("cells", []):
        lines += ["", "[[rf_config]]"]
        _emit_fields(lines, schema.RF_DEV, cell, replaying)

    lines += ["", "[dci_log_config]"]
    _emit_fields(lines, schema.LOG, model.get("log", {}), replaying)

    lines.append("")
    return "\n".join(lines)


def write(model, path):
    path = Path(path)
    path.write_text(dumps(model), encoding="utf-8")
    return str(path)


# --------------------------------------------------------------------------- reading


def _coerce(value, field):
    type_ = field["type"]
    try:
        if type_ == "bool":
            return bool(value)
        if type_ in ("int", "int64", "mode"):
            return int(value)
        return str(value)
    except (TypeError, ValueError):
        return field["default"]


def _read_fields(fields, table):
    out = {}
    for field in fields:
        key = field["key"]
        out[key] = _coerce(table[key], field) if key in table else field["default"]
    return out


def _restore_gui_extras(cell):
    """A config file carries only rf_freq. Show it in EARFCN terms when the frequency maps
    unambiguously to one EARFCN, otherwise leave the cell in Hz mode -- picking one of
    several overlapping bands would misrepresent what the file says."""
    cell.update(schema.GUI_CELL_EXTRAS)
    candidates = earfcn.freq_to_earfcns(cell.get("rf_freq", 0))
    if len(candidates) == 1:
        cell["gui_freq_mode"] = "earfcn"
        cell["gui_earfcn"] = candidates[0][0]
    return cell


def load(path):
    """Parse a config.toml into the GUI model. Unknown keys are dropped, missing keys
    fall back to the schema default -- the same thing the C reader does."""
    with open(path, "rb") as fh:
        root = tomllib.load(fh)

    cells = [_restore_gui_extras(_read_fields(schema.RF_DEV, dev))
             for dev in root.get("rf_config", []) or []]
    if not cells:
        cells = [schema.default_cell()]

    return {
        "schema_version": schema.STATE_VERSION,
        "top": _read_fields(schema.TOP_LEVEL, root),
        "log": _read_fields(schema.LOG, root.get("dci_log_config", {}) or {}),
        "cells": cells[: schema.MAX_NOF_RF_DEV],
    }


# --------------------------------------------------------------------------- validation


def validate(model, out_dir):
    """Mirror ngscope_config_finalize() (load_config.c:218-252) plus the schema's own
    bounds, so a bad setting shows up inline instead of as a process that exits at once.

    Returns (errors, warnings); each entry is {"where", "message"}.
    """
    errors, warnings = [], []

    def err(where, message):
        errors.append({"where": where, "message": message})

    def warn(where, message):
        warnings.append({"where": where, "message": message})

    top = model.get("top", {})
    cells = model.get("cells", [])

    # -- top level
    rnti = top.get("rnti", 0)
    if not isinstance(rnti, int) or not 0 <= rnti <= 65535:
        err("top.rnti", "RNTI must be between 0 and 65535.")
    elif rnti == 0:
        warn(
            "top.rnti",
            "RNTI 0 is not inert: it matches empty decoder-tree slots and floods the "
            "output.",
        )

    if top.get("rach_filter_only") and not top.get("decode_RAR"):
        warn(
            "top.decode_RAR",
            "rach_filter_only needs decode_RAR to populate the RNTI set -- ngscope will "
            "force decode_RAR on.",
        )

    # -- cells
    if not 1 <= len(cells) <= schema.MAX_NOF_RF_DEV:
        err("cells", f"Between 1 and {schema.MAX_NOF_RF_DEV} cells are required.")

    seen_freqs = {}
    for i, cell in enumerate(cells):
        where = f"cells.{i}"

        freq = cell.get("rf_freq", 0)
        by_earfcn = cell.get("gui_freq_mode") == "earfcn"

        if by_earfcn:
            # rf_freq is derived from the EARFCN, so report the problem where it was typed.
            try:
                entered = int(cell.get("gui_earfcn"))
            except (TypeError, ValueError):
                entered = None
            if entered is None:
                err(f"{where}.gui_earfcn", f"Cell {i + 1}: EARFCN is required.")
            elif earfcn.earfcn_to_freq(entered) is None:
                err(
                    f"{where}.gui_earfcn",
                    f"Cell {i + 1}: EARFCN {entered} is outside the valid range "
                    f"0..{earfcn.MAX_DL_EARFCN}.",
                )

        if not freq:
            if not by_earfcn:
                err(f"{where}.rf_freq", f"Cell {i + 1}: downlink frequency is required.")
        elif not earfcn.MIN_SANE_HZ <= freq <= earfcn.MAX_SANE_HZ:
            # Catches the classic slip of typing MHz (or an EARFCN) into a field in Hz.
            err(
                f"{where}.{'gui_earfcn' if by_earfcn else 'rf_freq'}",
                f"Cell {i + 1}: {freq / 1e6:g} MHz is outside the plausible LTE range "
                f"({earfcn.MIN_SANE_HZ / 1e6:g}-{earfcn.MAX_SANE_HZ / 1e9:g} GHz). "
                "The frequency is in Hz, so 2680 MHz is 2680000000.",
            )
        elif freq in seen_freqs:
            # ngscope_config_finalize() calls exit(0) on this, with no log file written.
            err(
                f"{where}.rf_freq",
                f"Cell {i + 1} shares its frequency with cell {seen_freqs[freq] + 1}. "
                "ngscope refuses to run two devices on the same frequency.",
            )
        else:
            seen_freqs[freq] = i

        n_id_2 = cell.get("N_id_2", -1)
        if not -1 <= n_id_2 <= 2:
            err(f"{where}.N_id_2", f"Cell {i + 1}: N_id_2 must be -1, 0, 1 or 2.")

        threads = cell.get("nof_thread", 4)
        if not 1 <= threads <= schema.MAX_NOF_DCI_DECODER:
            err(
                f"{where}.nof_thread",
                f"Cell {i + 1}: decoder threads must be 1..{schema.MAX_NOF_DCI_DECODER}.",
            )

        rf_args = cell.get("rf_args", "") or ""
        if len(rf_args) > schema.RF_ARGS_MAX_LEN:
            err(
                f"{where}.rf_args",
                f"Cell {i + 1}: RF args is {len(rf_args)} characters but the field holds "
                f"{schema.RF_ARGS_MAX_LEN}.",
            )

        mode = cell.get("mode", schema.MODE_NORMAL)
        replay = (cell.get("replay_fname") or "").strip()
        if mode == schema.MODE_REPLAY:
            if not replay:
                err(f"{where}.replay_fname", f"Cell {i + 1}: replay mode needs a file.")
            elif not Path(replay).is_file():
                err(f"{where}.replay_fname", f"Cell {i + 1}: {replay} does not exist.")

        if mode == schema.MODE_RECORD and cell.get("decode_pdcch"):
            warn(
                f"{where}.decode_pdcch",
                f"Cell {i + 1}: recording with PDCCH decoding on costs CPU that the "
                "capture may need. Turn it off for a pure IQ capture.",
            )

    # -- output directory (-o)
    if not out_dir:
        err("out_dir", "Choose an output directory.")
    else:
        path = Path(out_dir)
        if not path.is_dir():
            err("out_dir", f"{out_dir} is not a directory.")
        else:
            try:
                probe = path / ".ngscope-gui-write-test"
                probe.touch()
                probe.unlink()
            except OSError as exc:
                err("out_dir", f"{out_dir} is not writable: {exc.strerror}.")

    return errors, warnings
